[package]
name = "gen_lsb"
version = "0.1.3"
authors = ["Alexey Voznyuk <me@swizard.info>"]

[dependencies]
par_exec = { git = "https://github.com/swizard0/par_exec.git" }

[dev-dependencies]
rand = "0.3"
